on:
  create

jobs:
  pull-request:
    runs-on: ubuntu-latest
      - uses: actions/checkout@v2
      - name: pull-request
        uses: repo-sync/pull-request@v2
        with:
          destination_branch: "main"
